augment:
  brightness: 0.1
  contrast: 0.1
  hflip_p: 0.5
  rotate_angles:
  - 0
  - 90
  - 180
  - 270
  saturation: 0.1
  sharpness_factor: 2.0
  sharpness_p: 0.5
  vflip_p: 0.5
img_size: 224
mean:
- 0.485
- 0.456
- 0.406
num_classes: 2
num_workers: 12
pin_memory: true
repeat_factor: 5
std:
- 0.229
- 0.224
- 0.225
train_labels: /root/autodl-tmp/projects/myq/SingleCellProject/runs_5fold/fold4/singlecell/train_labels.txt
use_weighted_sampler: false
val_labels: /root/autodl-tmp/projects/myq/SingleCellProject/runs_5fold/fold4/singlecell/val_labels.txt
