arch: efficientnet_b0
pretrained: false
local_weight_path: /root/autodl-tmp/projects/myq/SingleCellProject/outputs/260323_wcore_19class_576_0.65_onlineAug/epoch=44-val_f1_macro=0.0000.ckpt
drop: 0.3
drop_path: 0.1
freeze_backbone_epochs: 5

# style-invariant training
mixstyle_prob: 0.0
mixstyle_alpha: 0.1
