output_root: /root/autodl-tmp/projects/myq/SingleCellProject/runs_5fold/fold1/cls_stage1_gt2yolo
batch_size: 512
max_epochs: 30
precision: 16-mixed
devices: 1
accumulate_grad_batches: 1
seed: 42
use_wandb: true
optimizer:
  name: adamw
  lr: 5e-5
  weight_decay: 1e-3
scheduler:
  name: cosine
  warmup_epochs: 5
callbacks:
  early_stopping:
    monitor: val/acc_weighted
    mode: max
    patience: 10
    min_delta: 1.0e-05
  checkpoint:
    monitor: val/acc_weighted
    mode: max
    save_top_k: 3
    filename: '{epoch:02d}-{val_acc_weighted:.4f}'
    save_last: true
