output_root: /root/autodl-tmp/projects/myq/SingleCellProject/outputs/260323_16class_logit_adjusted_ce_tau0
batch_size: 512
max_epochs: 50
precision: 16-mixed
devices: 1
accumulate_grad_batches: 1
seed: 42
use_wandb: true
optimizer:
  name: adamw
  lr: 5e-5
  weight_decay: 1e-3
scheduler:
  name: cosine
  warmup_epochs: 5
callbacks:
  early_stopping:
    monitor: val/f1_macro
    mode: max
    patience: 10
    min_delta: 1.0e-05
  checkpoint:
    monitor: val/f1_macro
    mode: max
    save_top_k: 3
    filename: '{epoch:02d}-{val_f1_macro:.4f}'
    save_last: true
imbalance:
  use_class_weight_loss: False
  loss: logit_adjusted_ce  # core | weighted_ce | logit_adjusted_ce
  logit_adjust_tau: 0
  label_smoothing: 0.05
