arch: efficientnet_b0
pretrained: false
local_weight_path: /root/autodl-tmp/projects/myq/SingleCellProject/weights/pytorch_model.bin
drop: 0.3
drop_path: 0.1
freeze_backbone_epochs: 5

# style-invariant training
mixstyle_prob: 0
mixstyle_alpha: 0.1
