# baseline
advanced:
  # only image_only is supported
  input_mode: image_only

  # A: center prior / border suppression
  center_weight_mode: none # none | gaussian | elliptical
  center_weight_strength: 0.35
  center_weight_sigma: 0.45

  border_aug_prob: 0
  border_aug_width_ratio: 0.12
  border_aug_mode: low_contrast # blur | low_contrast | random_mask | mean_color
model:
  mixstyle_prob: 0.0
train:
  attention_regularization:
    use_border_attention_reg: false
