# center/border only
advanced:
  input_mode: image_only
  center_weight_mode: gaussian
  center_weight_strength: 0.45
  center_weight_sigma: 0.45
  border_aug_prob: 0.6
  border_aug_width_ratio: 0.12
  border_aug_mode: low_contrast
  use_stain_normalization: false
  use_he_channels: false
  use_size_branch: false
model:
  mixstyle_prob: 0.4
train:
  attention_regularization:
    use_border_attention_reg: true
    lambda_border: 0.05
    lambda_center: 0.02
    border_ratio: 0.15
