accumulate_grad_batches: 1
batch_size: 512
callbacks:
  checkpoint:
    filename: '{epoch:02d}-{val_acc_macro:.4f}'
    mode: max
    monitor: val/acc_macro
    save_last: true
    save_top_k: 3
  early_stopping:
    min_delta: 1.0e-05
    mode: max
    monitor: val/acc_macro
    patience: 10
devices: 1
max_epochs: 30
optimizer:
  lr: 5.0e-05
  name: adamw
  weight_decay: 0.001
output_root: /root/autodl-tmp/projects/myq/SingleCellProject/runs_5fold/fold2/cls_stage2_yolo2yolo
precision: 16-mixed
scheduler:
  name: cosine
  warmup_epochs: 5
seed: 42
use_wandb: true
